/*
 * 
 *  Class that will act as a tuple that will represent a private
 *  key generated by the RSA algorithm
 *  
 */
package Securitypkg;

class PrivateKey
{
	// key, val pair for decryption
	private int n;
	private int d;
	
	// Constructor
	// @Param - n = computed by the the given prime numbers  p and q
	// @Param - e = computed through extended euclidian algorithm(big values) or through trial and error(small values)
	public PrivateKey(int n, int d)
	{
		this.n = n;
		this.d = d;
	}
	
	// getter
	public int getN()
	{
		return n;
	}
	
	// getter
	public int getD()
	{
		return d;
	}
	
}
