/*
 * 
 *  Class that will act as a tuple that will represent a public
 *  key generated by the RSA algorithm
 *  
 */
package Securitypkg;

class PublicKey
{
	//  key, val pair for encryption
	private int n;
	private int e;
	
	// Constructor
	// @Param - n = computed by the the given prime numbers  p and q
	// @Param - e = computed by finding the GCD of p and q
	public PublicKey(int n, int e)
	{
		this.n = n;
		this.e = e;
	}
	
	// getter
	public int getN()
	{
		return n;
	}
	
	// getter
	public int getE()
	{
		return e;
	}
}
